name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub App Token
        id: token
        uses: actions/create-github-app-token@v3.1.1
        with:
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          client_id: ${{ secrets.GH_APP_CLIENT_ID }}

      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ steps.token.outputs.token }}